### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DimaRazb** [danmarg/sts-mate#12]
Hi, any idea why it keeps restarting? Great product btw, thanks mate!
![image](https://github.com/danmarg/sts-mate/assets/29647985/6d3efee0-cd77-47be-822b-615b8a19645c)

**Comment by danmarg** [comment]
Seems like the format of Go boolean flags changed sometime in the last few years, and instead of —nohttp in the Dockerfile, it should be —http=false.

Do you mind trying that and telling me if it works?

**Comment by danmarg** [comment]
5cc5ebaefaedd2f754c1c6780350b5f0abbeedc9

**Comment by danmarg** [comment]
Should work now. :) Thanks for the report.
