### ISSUE TITLE
fail after Let's Encrypt tlsalpnrevocation?

### ISSUE THREAD

**Issue by andreasschulze** [danmarg/sts-mate#6]
after https://letsencrypt.org/tlsalpnrevocation/ I see these kind of errors in sts-mate:
```
 /mta-sts-server --my_real_host mta-sts.examle --sts_mx mta.example --sts_mode none --sts_max_age 3600 --acme_endpoint https://acme-staging-v02.api.letsencrypt.org/directory
2022/01/30 22:28:57 http: TLS handshake error from [2001:db8::2]:34618: acme/autocert: unable to satisfy "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1563274858" for domain "mta-sts.example": no viable challenge type found
2022/01/30 22:29:44 http: TLS handshake error from [2001:db8::1]:37018: acme/autocert: missing certificate
```
maybe an issue with the golang implementation? Using golang-1.17.6 here ...

**Comment by andreasschulze** [comment]
btw: https://github.com/danmarg/sts-mate/blob/master/main.go#L158 should be updated

**Comment by andreasschulze** [comment]
[forcing TLS1.2+](https://github.com/andreasschulze/sts-mate/compare/master...andreasschulze:issue_6?expand=1) does not solve the issue

**Comment by danmarg** [comment]
caveat: I don't know anything about this.

Is it possible to get a log of the challenge type that Let's Encrypt is serving? Looking at the [source](https://go.googlesource.com/crypto/+/master/acme/autocert/autocert.go), it seems like that's not logged here, but it's [this](https://go.googlesource.com/crypto/+/master/acme/types.go#467) JSON blob--I guess you could also just rebuild while adding logging to [here](https://go.googlesource.com/crypto/+/master/acme/autocert/autocert.go#805). 

Does this happen in prod, or just staging?

**Comment by andreasschulze** [comment]
I've no idea how to build sts-mate with modifications in acme/autocert

But to eliminate some common bitfalls I just setup sts-mate on a host the not used TLS-ALPN-01 recently
```
2022/02/01 14:53:45 http: TLS handshake error from [2a00:db8::1]:13087: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/74156330340" for domain "ergeht.example": no viable challenge type found
```

I'll now try an [other acme client](https://acme.sh) at the same host ...

**Comment by andreasschulze** [comment]
```
# acme.sh --version
https://github.com/acmesh-official/acme.sh
v3.0.2
```
->  latest ...

`acme.sh --issue --domain ergeht.example --alpn --server letsencrypt_test` works (as well as with `--server letsencrypt` = LE-PROD)

To me it looks like LE made some changes incompatible with acme/autocert or the way acme/autocert is used in sts-mate

@danmarg could you ping some golang people?

**Comment by andreasschulze** [comment]
btw: sts-mail fail in prod and staging

**Comment by danmarg** [comment]
I suspect the best way to do this would be to have a minimal repro and file a bug on https://github.com/golang/go/issues. 

https://github.com/golang/go/issues/37489 happens to have a nice minimal example. 

I unfortunately don't have a lot of time this week--if you don't get to it by this weekend I can try to take a stab. How's that sound?

**Comment by andreasschulze** [comment]
that's fine, I'll try it ...

**Comment by andreasschulze** [comment]
go.mod contain [this line](https://github.com/danmarg/sts-mate/blob/master/go.mod#L3), a 3 years old `acme/autocert` ?

**Comment by andreasschulze** [comment]
example at golang/go#37489 works

**Comment by danmarg** [comment]
Ah, of course. 

9b027f6

**Comment by danmarg** [comment]
Let me know if that doesn't fix it. :)

**Comment by andreasschulze** [comment]
now it works again. May thanks!

May I ask
 - which commands did you use to update go.[mod|sum]
 - what are other reasons for such updates?
 - which criteria other than my user-complaint should trigger an update of go.[mod|sum]?
 - may we see a similar problem in 2 years?
 
 Could you suggest documentation for my unterstanding? I've not really knowlege about the role go.[mod|sum] really play...

**Comment by danmarg** [comment]
Sure. This is due to go [module](https://go.dev/blog/using-go-modules) versioning, which I'm honestly only passingly familiar with.

For each dependency, I just upgraded to the latest, e.g. 

`go get golang.org/x/net@latest`

I think if I were making regular releases of this tool, I'd upgrade to `@latest` at each release and run through tests and staging before releasing, but this repo has no tests or anything. ;)

That said, it seems to me that this particular issue--of incompatibility with Lets Encrypt--can equally arise from running an out of date binary. So maybe what a real pro would do here is something like:

1. Have tests
2. Have a CI pipeline that exercises those tests
3. Have regular builds that update to `@latest`, runs those tests, and either creates a new release branch or creates new binaries
4. Have regular deployments of the Docker image that use those new releases

Or something like that.
