### ISSUE TITLE
Disable TLS1.0 and TLS1.1?

### ISSUE THREAD

**Issue by andreasschulze** [danmarg/sts-mate#9]
The server offers deprecated TLS version 1.0 and 1.1

Technically, it's no challenge to update `sts-mate` and disable these protocols. But:

- [RFC 8461](https://www.rfc-editor.org/rfc/rfc8461.html#section-7.2) say "an MTA-STS Server must implement TLS1.2 or higher"
- [RFC 8996](https://www.rfc-editor.org/rfc/rfc8996.html) deprecate TLS1.0 and 1.1

So, I _think_, it is OK to disable these protocols here, too

@danmarg could you confirm? Then I would take the job of adopting RFC 8996 for sts-mate

**Comment by danmarg** [comment]
I guess that's fine? 

https://github.com/golang/go/issues/45428 seems to suggest an unclear roadmap to deprecating TLS1.0/1.1 on the server, and https://pkg.go.dev/crypto/tls#Config says the default is 1.0 (as you noted). 

As you say, the RFC specifies that any MTA implementing MTA-STS (which I think includes *sending* servers, i.e. those fetching policies) must support 1.2/1.3. So this should be safe. 

I think it's fine to disable these protocols. It's probably also the case that people implementing MTA-STS tend to have modern TLS libraries. ;)

I would appreciate it if you make this change!

**Comment by danmarg** [comment]
Fixed thanks to your 5ea1415f8a43bbbb556f978dd2bf14b1525de443
